// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKKXVCoCgVrQcgROkxuNbLN4nnx6r-3o',
    appId: '1:782279695085:web:2c57381ba8a33f38b70ae4',
    messagingSenderId: '782279695085',
    projectId: 'carisma-4f6c6',
    authDomain: 'carisma-4f6c6.firebaseapp.com',
    storageBucket: 'carisma-4f6c6.firebasestorage.app',
    measurementId: 'G-J1K2S8DET6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5z6Zs0uY7l7jIpbq5ATx2ks2WXGSthUc',
    appId: '1:782279695085:android:fb754e15e975d440b70ae4',
    messagingSenderId: '782279695085',
    projectId: 'carisma-4f6c6',
    storageBucket: 'carisma-4f6c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIfoQlVeHmsmtSU78ahpyTpxlZCoMVqew',
    appId: '1:782279695085:ios:49b9daaf584d4dfeb70ae4',
    messagingSenderId: '782279695085',
    projectId: 'carisma-4f6c6',
    storageBucket: 'carisma-4f6c6.firebasestorage.app',
    iosBundleId: 'com.example.carisma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIfoQlVeHmsmtSU78ahpyTpxlZCoMVqew',
    appId: '1:782279695085:ios:49b9daaf584d4dfeb70ae4',
    messagingSenderId: '782279695085',
    projectId: 'carisma-4f6c6',
    storageBucket: 'carisma-4f6c6.firebasestorage.app',
    iosBundleId: 'com.example.carisma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYKKXVCoCgVrQcgROkxuNbLN4nnx6r-3o',
    appId: '1:782279695085:web:c12c457ca617c9f9b70ae4',
    messagingSenderId: '782279695085',
    projectId: 'carisma-4f6c6',
    authDomain: 'carisma-4f6c6.firebaseapp.com',
    storageBucket: 'carisma-4f6c6.firebasestorage.app',
    measurementId: 'G-968GB6WM45',
  );
}
